### ISSUE TITLE
Change transitions to verbs

### ISSUE THREAD

**Issue by tacman** [lyrixx/SFLive-Paris2016-Workflow#14]
I think the transition names should be verbs.  In particular, in the task workflow 'done' is a state, but 'finish' is a verb that would make sense for the transition.  Plus, having a transition and a state as the same word is possible, but might be confusing.

Similarly, I think 'process' is a better term to use than 'processing', which sounds like a state.

Happy to make those changes and submit a PR.

**Comment by lyrixx** [comment]
You are totally right.

I will be glad to merge your PR.

**Comment by tacman** [comment]
I expanded the task workflow and changed the terminology a bit:

![image](https://user-images.githubusercontent.com/619585/42386322-30e61ef2-810d-11e8-954d-3705cb8db043.png)

I've been thinking about a Symfony 4 demo project that is a web crawler, and the idea is that when crawling links they might temporarily fail (server busy, etc.) or permanently fail (no route to domain, etc.), and this workflow reflects that.
