### ISSUE TITLE
Add link to workflow component documentation

### ISSUE THREAD

**Issue by tacman** [lyrixx/SFLive-Paris2016-Workflow#2]
Can you add a link to the documentation of the component?  I can never seem to find it, and there are way too many search results for it on symfony.com.

http://symfony.com/search?q=workflow+component&src={referrer:source?}

Thanks, love this component, may switch to 3.2 early just to start using it.

**Comment by lyrixx** [comment]
Hello.

Unfortunately, the documentation does not exist yet :(

You can follow [this thread](https://github.com/symfony/symfony-docs/issues/6677)  to get updated as soon as something is comming.
