### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by GromNaN** [lyrixx/SFLive-Paris2016-Workflow#7]
Hi @lyrixx,

It might be a temporary issue, I get an error page on the demo website linked in this repository :
http://symfony-workflow-demo.herokuapp.com/article

**Comment by lyrixx** [comment]
Yes Thanks for the notice.
I know. I broke it this morning and I don't know how to fix it. I upgraded to SF4 + Flex and :boom: 

I pinged David but I did not take time yet to fix it [ref](https://twitter.com/dzuelke/status/978989488574640130)

**Comment by lyrixx** [comment]
It's not fixed. Thanks again ;) http://symfony-workflow-demo.herokuapp.com/
